spring:
  jpa.hibernate.ddl-auto: update
  spring.jpa.hibernate.ddl-auto: validate
  datasource:
    dirverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ejercicio4?createDatabaseIfNotExist=true
    username: root
    password: 123456Aa-
  hikari:
    connection-timeout: 60000
    maximum-pool-size: 5
logging:
  pattern.console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  level.org.hibernate.SQL: debug
  level: debug
